name: Rust CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "tests/**"
      - "bytecode-spec.md"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "tests/**"
      - "bytecode-spec.md"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo test --workspace
